graphql:
  handler: src/functions/graphql/query/handler.execute
  events:
    - http:
        path: query
        method: get
    - http:
        path: query
        method: post
        cors: true

  environment:
    MYSQLDB_URL: ${self:custom.MYSQLDB_URL}
    MYSQLDB_NAME: ${self:custom.MYSQLDB_NAME}
    MYSQLDB_USERNAME: ${self:custom.MYSQLDB_USERNAME}
    MYSQLDB_PASSWORD: ${self:custom.MYSQLDB_PASSWORD}
    MYSQLDB_PORT: ${self:custom.MYSQLDB_PORT}
  warmup:
    api:
      enabled: 'prod'
